name: haskell

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.0', '8.2', '8.4', '8.6', '8.8', '8.10', '9.0', '9.2', '9.4', '9.6', '9.8']
        os: ['ubuntu-latest']
        include:
        - os: macos-latest
          ghc: '9.8'
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id:   setup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-update: true
    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-build-
          ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-
          ${{ runner.os }}

    - name: Install dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test --enable-tests  --enable-benchmarks all
    - name: Build Docs
      run: cabal haddock --disable-documentation
